type School = {
  id: string; name: string; short: string; location: string; state: string;
  division: string; conference: string; setting: string; climate: string;
  size: string; flightLocation: string;
  aviation: string; ratp: string; fleet: string; partners: string;
  cost: string; flightCost: string; xc: string;
  times: { scholarship: string; recruit: string; walkon: string };
  pros: string[]; cons: string[]; notes: string;
  scores: { aviation: number; athletics: number; value: number; climate: number; campus: number };
  sources: { label: string; url: string }[];
};

const schools: School[] = [
  {
    id: "auburn", name: "Auburn University", short: "AU", location: "Auburn, Alabama", state: "AL",
    division: "NCAA Division I", conference: "SEC", setting: "Large college town; traditional flagship campus",
    size: "About 35,200 students (Fall 2025). This is a large university with major-school facilities and crowds.",
    flightLocation: "Auburn's aviation program is part of the main university. Flight training uses the university-owned Auburn University Regional Airport, a short drive from the central campus—not a separate satellite college.",
    climate: "Hot, humid summers; mild winters; thunderstorms can interrupt summer flying.",
    aviation: "B.S. Professional Flight, Part 141 and AABI-accredited. Integrated private through commercial multi-engine, with CFI electives and turbine/crew preparation.",
    ratp: "Yes — 1,000-hour pathway with qualifying degree/coursework", fleet: "University-operated glass-cockpit training fleet; confirm current mix during tour.",
    partners: "Delta Propel and other airline/cadet relationships; offerings and eligibility change.",
    cost: "Public flagship pricing; use Auburn's current estimator for residency-specific COA.", flightCost: "Flight course fees are additional and variable by proficiency.",
    xc: "High-level SEC distance program. A roster conversation generally requires nationally competitive track marks.",
    times: { scholarship: "4:08 / 8:55", recruit: "4:15 / 9:15", walkon: "4:22 / 9:30" },
    pros: ["SEC resources and strong school spirit", "Integrated R-ATP professional-flight degree", "Warm-weather outdoor training"],
    cons: ["Most demanding running fit in this directory", "Selective flight-program capacity", "Heat, humidity and convective weather"],
    notes: "Best for a runner who is already a clear Division I recruit and wants a major-college experience.",
    scores: { aviation: 9, athletics: 10, value: 7, climate: 7, campus: 9 },
    sources: [{ label: "Professional Flight", url: "https://cla.auburn.edu/aviation/our-programs/professional-flight/" }, { label: "Men's XC", url: "https://auburntigers.com/sports/cross-country" }]
  },
  {
    id: "baylor", name: "Baylor University", short: "BU", location: "Waco, Texas", state: "TX",
    division: "NCAA Division I", conference: "Big 12 Conference", setting: "Private Christian research university on a traditional riverside campus in a mid-sized Texas city",
    size: "About 19,858 undergraduate and graduate students (Fall 2025). It offers a major-university experience with a strong residential campus identity.",
    flightLocation: "Aviation classes are part of Baylor's main Waco campus. Flight training is conducted at the Baylor University Flight Center at Waco Regional Airport, an off-campus facility that requires personal transportation.",
    climate: "Hot summers, mild winters and long outdoor-training seasons; heat, wind and thunderstorms can affect running and flying.",
    aviation: "B.S. in Aviation Sciences, Professional Pilot concentration, with fixed-wing and helicopter options. Fixed-wing students complete private, instrument, commercial and CFI training, with a CFII or multi-engine option.",
    ratp: "Yes — qualifying fixed-wing graduates can receive a 500-hour reduction and pursue the 1,000-hour R-ATP route", fleet: "Flight training is operated for Baylor by Universal Flight Concepts. Published fixed-wing aircraft include Tecnam P2008, P2010 and multi-engine P2006 models; confirm the current fleet and dispatch availability.",
    partners: "Published pilot-pipeline partners include Southwest Destination 225°, Envoy, SkyWest, Cape Air and Mesa.",
    cost: "For 2026–27, Baylor publishes $67,756 in annual tuition and required fees, plus average room and meals near $17,222 before aid.", flightCost: "Baylor's 2026–27 fixed-wing course estimate totals about $155,895 in addition to university costs. Actual training expense varies with student progress.",
    xc: "Big 12 Division I distance program with a small, competitive men's roster. Strong national-level marks are generally needed to begin a serious recruiting conversation.",
    times: { scholarship: "4:08 / 8:55", recruit: "4:15 / 9:12", walkon: "4:23 / 9:30" },
    pros: ["Professional Pilot degree with a 1,000-hour R-ATP route", "Southwest and regional-airline pathways", "Big 12 athletics and a strong traditional campus experience"],
    cons: ["Very high tuition plus published flight-course costs", "Limited and competitive flight slots", "Airport transportation must fit around practice and team travel"],
    notes: "A strong aviation and campus option for an academically qualified, high-level Division I runner; cost and admission to a limited flight slot are the biggest questions.",
    scores: { aviation: 9, athletics: 9, value: 4, climate: 7, campus: 9 },
    sources: [{ label: "Professional Pilot", url: "https://aviation.ecs.baylor.edu/undergraduate-programs/bachelor-science-aviation-sciences/aviation-sciences/professional-pilot" }, { label: "Flight costs", url: "https://aviation.ecs.baylor.edu/about-us/baylor-university-flight-center/flight-training-costs" }, { label: "Airline partners", url: "https://aviation.ecs.baylor.edu/about-us/institutional-memberships-and-program-partners" }, { label: "Men's XC", url: "https://baylorbears.com/sports/cross-country" }]
  },
  {
    id: "erau-daytona", name: "Embry-Riddle Aeronautical University — Daytona Beach", short: "ERAU-D", location: "Daytona Beach, Florida", state: "FL",
    division: "NCAA Division II", conference: "Sunshine State Conference", setting: "Small aviation-centered campus near the coast and an international airport",
    size: "About 8,750 students at the Daytona Beach residential campus (Fall 2025, undergraduate and graduate).",
    flightLocation: "Flight operations are at Daytona Beach International Airport, directly beside the main Daytona Beach campus. Students do not commute to a separate satellite campus.",
    climate: "Warm year-round; hot, humid and stormy summers; hurricane-season planning matters.",
    aviation: "B.S. Aeronautical Science with deeply integrated, university-run flight training and extensive simulators. Aviation is central to campus life.",
    ratp: "Yes — 1,000-hour pathway with qualifying coursework", fleet: "Large university fleet and simulators based at Daytona Beach International Airport.",
    partners: "Multiple airline pathways and a large aviation alumni network.",
    cost: "2026–27 on-campus academic COA published near $70,686 before flight training.", flightCost: "University guide reported a roughly $89,032 median private-through-commercial track; current quotes should replace planning figures.",
    xc: "Competitive Division II program with year-round training. More accessible than Power-conference DI, but roster quality is strong.",
    times: { scholarship: "4:17 / 9:15", recruit: "4:25 / 9:35", walkon: "4:35 / 9:55" },
    pros: ["Aviation-first culture and network", "Airport-adjacent training model", "DII athletic opportunity in a warm climate"],
    cons: ["High combined academic and flight cost", "Flight and varsity schedules both demand flexibility", "Storm and hurricane disruptions"],
    notes: "One of the clearest aviation-plus-athletics matches; verify that flight blocks can coexist with team practice and travel.",
    scores: { aviation: 10, athletics: 8, value: 5, climate: 8, campus: 8 },
    sources: [{ label: "Aeronautical Science", url: "https://daytonabeach.erau.edu/college-aviation/aeronautical-science" }, { label: "Costs", url: "https://erau.edu/admissions/tuition-and-costs" }, { label: "Men's XC", url: "https://erauathletics.com/sports/mens-cross-country" }]
  },
  {
    id: "erau-prescott", name: "Embry-Riddle Aeronautical University — Prescott", short: "ERAU-P", location: "Prescott, Arizona", state: "AZ",
    division: "NAIA", conference: "California Pacific Conference", setting: "Small aviation-centered campus in a high-desert mountain town",
    size: "About 3,270 students at the Prescott residential campus (Fall 2025, undergraduate and graduate).",
    flightLocation: "Academic classes are on the main Prescott campus. Flight training is at Prescott Regional Airport, reached by a short drive; it is an off-campus flight facility, not another university campus.",
    climate: "Four seasons, low humidity and many sunny days; altitude near 5,000 feet shapes running and flight performance.",
    aviation: "B.S. Aeronautical Science with integrated flight courses, simulators and high-density-altitude experience.",
    ratp: "Yes — 1,000-hour pathway with qualifying coursework", fleet: "University-operated aircraft and simulators at Prescott Regional Airport.",
    partners: "Airline pathways plus Embry-Riddle's national aviation alumni base.",
    cost: "2026–27 on-campus academic COA published near $70,686 before flight training.", flightCost: "Flight charges are separate and proficiency-dependent; request a current course-by-course estimate.",
    xc: "NAIA program with strong altitude-training appeal and typically more recruiting flexibility than elite DI teams.",
    times: { scholarship: "4:22 / 9:25", recruit: "4:32 / 9:50", walkon: "4:45 / 10:15" },
    pros: ["High-altitude running and flying", "Aviation-focused environment", "NAIA aid flexibility"],
    cons: ["High private-school plus flight cost", "Smaller town and campus", "Altitude acclimation and occasional winter weather"],
    notes: "Especially attractive for an Arizona-based student who values altitude, small classes and aviation immersion.",
    scores: { aviation: 10, athletics: 7, value: 5, climate: 9, campus: 8 },
    sources: [{ label: "Aeronautical Science", url: "https://prescott.erau.edu/college-aviation/aeronautical-science" }, { label: "R-ATP authorization", url: "https://prescott.erau.edu/-/media/files/prescott/college-of-aviation/r-atp-letter-of-authorization.pdf" }, { label: "Men's XC", url: "https://erauathletics.com/sports/mens-cross-country" }]
  },
  {
    id: "florida-tech", name: "Florida Institute of Technology", short: "Florida Tech", location: "Melbourne, Florida", state: "FL",
    division: "NCAA Division II", conference: "Sunshine State Conference", setting: "Private STEM-focused campus on Florida's Space Coast",
    size: "About 3,800 full-time, degree-seeking undergraduates (Fall 2025). It has a smaller, STEM-focused college feel.",
    flightLocation: "Classes are based at the main Melbourne campus. FIT Aviation operates at Melbourne Orlando International Airport about 2.5 miles away, so flight students make a short off-campus trip.",
    climate: "Warm coastal climate; humid summers, frequent afternoon storms and hurricane exposure.",
    aviation: "Aeronautical Science–Flight degree delivered with FIT Aviation at Melbourne Orlando International Airport under Part 141.",
    ratp: "Yes — qualifying aviation degree/coursework; confirm 1,000 vs. 1,250-hour track", fleet: "All-Piper fleet including Warrior, Archer, Pilot 100i and Seminole, with glass avionics.",
    partners: "Published pathways include United Aviate, Delta Propel, JetBlue, Allegiant, Envoy, PSA, Frontier and Republic.",
    cost: "Private-university pricing; consult the current net-price calculator.", flightCost: "Additional FIT Aviation flight fees vary by course and proficiency.",
    xc: "Competitive DII program in the SSC, often a realistic target for strong varsity runners.",
    times: { scholarship: "4:20 / 9:20", recruit: "4:30 / 9:45", walkon: "4:42 / 10:10" },
    pros: ["Very broad airline pathway list", "Airport training close to campus", "Space Coast aerospace ecosystem"],
    cons: ["Private tuition plus flight fees", "Heat and humidity for distance training", "Weather interruptions in storm season"],
    notes: "A high-upside aviation option for a DII-caliber runner; compare net aid directly with Embry-Riddle Daytona.",
    scores: { aviation: 9, athletics: 7, value: 5, climate: 8, campus: 8 },
    sources: [{ label: "Fleet & facilities", url: "https://www.fit.edu/aeronautics/about-us/facilities/" }, { label: "Airline pathways", url: "https://www.fit.edu/aeronautics/academics-and-learning/pathway-programs/" }, { label: "Men's XC", url: "https://floridatechsports.com/sports/mens-cross-country" }]
  },
  {
    id: "kent-state", name: "Kent State University", short: "Kent State", location: "Kent, Ohio", state: "OH",
    division: "NCAA Division I", conference: "Mid-American Conference", setting: "Large public campus in a classic college town near Cleveland",
    size: "About 24,930 students at the Kent Campus (Fall 2025); the full Kent State system enrolled about 33,319.",
    flightLocation: "The degree is based at the main Kent Campus. Flying happens at the university-owned Kent State University Airport in nearby Stow, a short drive away—not at a separate academic satellite campus.",
    climate: "Four seasons; cold, cloudy and snowy winters; productive spring-through-fall flying windows.",
    aviation: "B.S. Professional Pilot in an AABI-accredited, Part 141 university program at Kent State University Airport.",
    ratp: "Yes — qualifying Professional Pilot graduates can pursue reduced-hour R-ATP", fleet: "University training fleet with modern avionics; verify the current aircraft count and types on a tour.",
    partners: "Career relationships and cadet pathways vary; confirm current active agreements.",
    cost: "Public-university tuition with lower in-state pricing; flight fees are separate.", flightCost: "Course-based flight fees; ask for a completion-cost range, not only minimum syllabus cost.",
    xc: "Mid-major Division I. A strong runner can be viable without Power-conference marks, subject to roster space.",
    times: { scholarship: "4:13 / 9:05", recruit: "4:22 / 9:25", walkon: "4:30 / 9:45" },
    pros: ["Strong public-school value potential", "University airport and established program", "More attainable DI running tier"],
    cons: ["Winter weather can affect flight cadence", "DI roster competition", "Program demand may constrain flight slots"],
    notes: "A strong value candidate, especially for Midwest residents seeking DI athletics and integrated flight training.",
    scores: { aviation: 8, athletics: 8, value: 8, climate: 5, campus: 8 },
    sources: [{ label: "Professional Pilot", url: "https://www.kent.edu/cae/professional-pilot" }, { label: "Men's XC", url: "https://kentstatesports.com/sports/cross-country" }, { label: "Costs", url: "https://www.kent.edu/tuition" }]
  },
  {
    id: "louisiana-tech", name: "Louisiana Tech University", short: "LA Tech", location: "Ruston, Louisiana", state: "LA",
    division: "NCAA Division I", conference: "Conference USA", setting: "Medium public university in a small Southern college town",
    size: "About 12,145 students (Fall 2025). It is a mid-sized university in a small college town.",
    flightLocation: "Academic classes are on Louisiana Tech's main Ruston campus. Flight operations are headquartered at Ruston Regional Airport, an off-campus facility a short drive east of town.",
    climate: "Long, hot and humid summers; mild winters; thunderstorms can disrupt training and flying.",
    aviation: "AABI-accredited B.S. Professional Aviation with year-round Part 141 ground, simulator and flight training at Ruston Regional Airport.",
    ratp: "Yes — verify current FAA-approved credit/hour pathway with program", fleet: "Published fleet includes Cessna Skyhawks and Piper Arrows; confirm current additions and multi-engine inventory.",
    partners: "Published relationships include Southwest, SkyWest, Republic, Mesa, Cape Air and Purple Runway.",
    cost: "Public-university pricing and typically attractive regional value; residency affects tuition.", flightCost: "A separate flight-fee schedule applies; obtain the current version before comparing.",
    xc: "DI mid-major environment with a wider performance window than the SEC or Big Ten.",
    times: { scholarship: "4:16 / 9:10", recruit: "4:25 / 9:35", walkon: "4:36 / 9:58" },
    pros: ["Potentially strong total-cost value", "Long-established AABI program", "Multiple airline relationships"],
    cons: ["Small-town setting", "Heat and humidity", "Fleet information should be reconfirmed in person"],
    notes: "An underrated value school to investigate early; ask coaches about roster needs for the student's graduation year.",
    scores: { aviation: 8, athletics: 7, value: 9, climate: 6, campus: 7 },
    sources: [{ label: "Professional Aviation", url: "https://liberalarts.latech.edu/Professional-Aviation/" }, { label: "Men's XC", url: "https://latechsports.com/sports/cross-country" }]
  },
  {
    id: "mtsu", name: "Middle Tennessee State University", short: "MTSU", location: "Murfreesboro, Tennessee", state: "TN",
    division: "NCAA Division I", conference: "Conference USA", setting: "Large public campus in a fast-growing city near Nashville",
    size: "About 20,500 students (2024–25). It offers a large-campus experience without being as huge as Purdue or Auburn.",
    flightLocation: "Aerospace classes are part of MTSU's main Murfreesboro campus. Aircraft and flight labs operate at Murfreesboro Municipal Airport, a short drive north of campus.",
    climate: "Four-season but generally mild; hot humid summers, occasional winter ice, thunderstorms.",
    aviation: "B.S. Aerospace, Professional Pilot concentration; AABI-accredited Part 141 training with glass cockpits and CRJ-700 training device.",
    ratp: "Yes — up to 500-hour reduction; qualifying graduates may reach R-ATP at 1,000 hours", fleet: "University aircraft at Murfreesboro Municipal Airport plus advanced flight-training devices.",
    partners: "Delta Propel, Southwest Destination 225° and other structured pathways.",
    cost: "Public-university pricing with in-state advantage; flight labs are additional.", flightCost: "Flight lab guide lists course costs; proficiency and repeats can raise totals.",
    xc: "Mid-major DI program; roster competitiveness varies by event group and recruiting class.",
    times: { scholarship: "4:14 / 9:05", recruit: "4:23 / 9:28", walkon: "4:33 / 9:50" },
    pros: ["Large, established aerospace department", "Major-airline pathway options", "Nashville-area access and internships"],
    cons: ["Large program can mean scheduling pressure", "Hot, humid summers", "DI roster is not guaranteed at benchmark"],
    notes: "A balanced public option with scale; specifically ask how athletes receive priority when flight blocks conflict with practice.",
    scores: { aviation: 9, athletics: 8, value: 8, climate: 7, campus: 8 },
    sources: [{ label: "Professional Pilot", url: "https://www.mtsu.edu/program/aerospace-professional-pilot-concentration-b-s/" }, { label: "Flight FAQ", url: "https://aerospace.mtsu.edu/flight-training-faqs/" }, { label: "Pathways", url: "https://aerospace.mtsu.edu/pathway-programs/" }, { label: "Men's XC", url: "https://goblueraiders.com/sports/mens-cross-country" }]
  },
  {
    id: "mankato", name: "Minnesota State University, Mankato", short: "Minn. State", location: "Mankato, Minnesota", state: "MN",
    division: "NCAA Division II", conference: "Northern Sun Intercollegiate Conference", setting: "Medium public university in a regional city",
    size: "About 15,720 students (Fall 2025). It is a mid-sized regional public university.",
    flightLocation: "Aviation academics are connected to the main Mankato campus. Hands-on flight training is provided with North Star Aviation at Mankato Regional Airport, an off-campus airport a short drive away.",
    climate: "Warm summers and cold, snowy winters; winter operations build weather judgment but can reduce flight cadence.",
    aviation: "B.S. Aviation with professional flight labs delivered with North Star Aviation at Mankato Regional Airport; AABI-accredited curriculum.",
    ratp: "Yes — curriculum supports the 60-credit, 1,000-hour R-ATP route", fleet: "Partner-operated training fleet at the regional airport; verify aircraft availability and dispatch metrics.",
    partners: "Sun Country pathway and North Star Aviation training partnership.",
    cost: "Public-university pricing; often compelling compared with private aviation schools.", flightCost: "Partner flight charges are additional; request a current zero-time-to-CFI estimate.",
    xc: "Established DII program. Athletic standards are strong but often attainable for a good varsity distance runner.",
    times: { scholarship: "4:18 / 9:18", recruit: "4:28 / 9:42", walkon: "4:42 / 10:08" },
    pros: ["Strong value potential", "DII recruiting fit", "All-season weather experience"],
    cons: ["Severe winter cold", "Training is delivered with an airport partner", "Smaller airline-network footprint than UND/ERAU"],
    notes: "A smart target for balancing cost, R-ATP eligibility and realistic DII athletic opportunity.",
    scores: { aviation: 8, athletics: 7, value: 9, climate: 4, campus: 7 },
    sources: [{ label: "Aviation B.S.", url: "https://ed.mnsu.edu/academic-programs/aviation/aviation-bs/" }, { label: "Aviation partners", url: "https://ed.mnsu.edu/academic-programs/aviation/aviation-bs/aviation-partners/" }, { label: "Men's XC", url: "https://msumavericks.com/sports/mens-cross-country" }]
  },
  {
    id: "purdue", name: "Purdue University", short: "Purdue", location: "West Lafayette, Indiana", state: "IN",
    division: "NCAA Division I", conference: "Big Ten Conference", setting: "Large research university in a major college town with its own airport",
    size: "About 58,000 students across Purdue's West Lafayette and Indianapolis locations (Fall 2024); Professional Flight is based in West Lafayette.",
    flightLocation: "This is a true main-campus flight setup. Purdue University Airport sits on the West Lafayette campus, so flight students do not travel to a satellite aviation campus.",
    climate: "Four seasons; humid summers, cold winters, wind and convective weather.",
    aviation: "B.S. Professional Flight through Purdue Polytechnic, with university-airport facilities and airline-oriented coursework.",
    ratp: "Yes — 1,000-hour R-ATP with 60 approved aviation credits", fleet: "University training aircraft and advanced simulators at Purdue University Airport; verify current fleet inventory.",
    partners: "United Aviate and additional industry relationships.",
    cost: "Public tuition; in-state is favorable, while flight fees add materially to published COA.", flightCost: "Course flight fees are additional and capacity is selective; request a four-year projection.",
    xc: "Big Ten program; this is one of the toughest athletic admissions in the directory.",
    times: { scholarship: "4:05 / 8:50", recruit: "4:12 / 9:05", walkon: "4:20 / 9:22" },
    pros: ["Elite academic and aviation brand", "Own airport and strong facilities", "Power-conference resources"],
    cons: ["Extremely competitive running roster", "Selective professional-flight admission", "Winter weather and high total workload"],
    notes: "Treat as a reach unless both academics and running marks are exceptional; apply to Professional Flight directly and early.",
    scores: { aviation: 10, athletics: 10, value: 8, climate: 5, campus: 10 },
    sources: [{ label: "Professional Flight", url: "https://polytechnic.purdue.edu/degrees/professional-flight" }, { label: "R-ATP course list", url: "https://polytechnic.purdue.edu/sites/default/files/files/R-ATP-Course%20List-Updated-12-14-22.pdf" }, { label: "United partnership", url: "https://polytechnic.purdue.edu/newsroom/purdue-united-airlines-establish-partnership-pilots-career-development" }, { label: "Men's XC", url: "https://purduesports.com/sports/cross-country" }]
  },
  {
    id: "siu", name: "Southern Illinois University Carbondale", short: "SIU", location: "Carbondale, Illinois", state: "IL",
    division: "NCAA Division I", conference: "Missouri Valley Conference", setting: "Public research university in a small town surrounded by forests and trails",
    size: "About 11,785 students (Fall 2025). It is a mid-sized university with a smaller-town atmosphere.",
    flightLocation: "Aviation is part of the main Carbondale university. Flight instruction takes place at Southern Illinois Airport, a nearby off-campus airport reached by a short drive.",
    climate: "Hot humid summers, cool winters and four seasons; occasional storms and winter disruptions.",
    aviation: "B.S. Aviation Flight with Part 141 university training and a broad School of Aviation ecosystem.",
    ratp: "Yes — qualifying graduates may receive a 250- or 500-hour reduction", fleet: "University flight-training aircraft and simulators at Southern Illinois Airport; confirm live dispatch data.",
    partners: "Published airline partners include United Aviate, SkyWest, Endeavor, Air Wisconsin and others.",
    cost: "Public-university pricing with comparatively strong value potential.", flightCost: "Flight fees are separate; compare estimated completion, instructor and checkride costs.",
    xc: "Missouri Valley DI program in a trail-rich setting; attainable target for a strong regional runner.",
    times: { scholarship: "4:13 / 9:03", recruit: "4:23 / 9:28", walkon: "4:34 / 9:52" },
    pros: ["Established R-ATP pathway", "Strong airline-partner list", "Trails and lower-cost college-town setting"],
    cons: ["Small-town location", "Variable Midwest weather", "Aviation and athletics scheduling requires explicit planning"],
    notes: "One of the best balance candidates for DI opportunity, aviation depth and cost; deserves an early coach conversation.",
    scores: { aviation: 9, athletics: 8, value: 9, climate: 6, campus: 7 },
    sources: [{ label: "Aviation Flight", url: "https://aviation.siu.edu/undergraduate/aviation-flight/" }, { label: "R-ATP", url: "https://aviation.siu.edu/r-atp.php" }, { label: "Airline partnerships", url: "https://aviation.siu.edu/about/airline-partnerships.php" }, { label: "Men's XC", url: "https://siusalukis.com/sports/mens-cross-country" }]
  },
  {
    id: "und", name: "University of North Dakota", short: "UND", location: "Grand Forks, North Dakota", state: "ND",
    division: "NCAA Division I", conference: "Summit League", setting: "Large public university in a small, aviation-centered northern city",
    size: "About 15,844 students (Fall 2025). The university is mid-sized, while its flight operation is unusually large.",
    flightLocation: "Aviation classes belong to UND's main Grand Forks campus. Most flight operations are at Grand Forks International Airport about 5 miles west, with regular transportation needed between campus and the airport.",
    climate: "Very cold, windy winters and warm summers; demanding weather builds operational experience but can affect dispatch.",
    aviation: "B.S. Aeronautics in Commercial Aviation at the John D. Odegard School; one of the country's largest collegiate flight operations.",
    ratp: "Yes — 1,000-hour route when all qualifying flight training and coursework are completed at UND", fleet: "Large standardized fleet; a 145-aircraft Piper replacement order begins deliveries in 2027.",
    partners: "Frontier, Sun Country and numerous regional/major airline pathways.",
    cost: "Public pricing; tuition varies by residency/program and flight fees add substantially.", flightCost: "Published course estimates should be totaled with fuel adjustments, checkrides and possible repeats.",
    xc: "Summit League DI program. Serious mid-major marks are generally needed for recruiting attention.",
    times: { scholarship: "4:12 / 9:00", recruit: "4:21 / 9:22", walkon: "4:31 / 9:45" },
    pros: ["Exceptional aviation scale and reputation", "Large fleet and deep alumni network", "Extensive real-world weather experience"],
    cons: ["Severe winter climate", "DI roster competition", "Large operation may feel less personal"],
    notes: "A top aviation benchmark school; the decision hinges on climate tolerance and genuine DI running fit.",
    scores: { aviation: 10, athletics: 8, value: 8, climate: 3, campus: 8 },
    sources: [{ label: "Commercial Aviation", url: "https://aero.und.edu/aviation/commercial-aviation/index.html" }, { label: "Airline pathways", url: "https://aero.und.edu/aviation/current-students/career-pathways.html" }, { label: "Men's XC", url: "https://fightinghawks.com/sports/mens-cross-country" }]
  },
  {
    id: "western-michigan", name: "Western Michigan University", short: "WMU", location: "Kalamazoo / Battle Creek, Michigan", state: "MI",
    division: "NCAA Division I", conference: "Mid-American Conference", setting: "Large public university; flight campus is about 25 miles from main campus",
    size: "About 17,331 students (Fall 2025). It is a mid-sized public university.",
    flightLocation: "This is the clearest satellite-campus setup in the guide. Most students live and take general classes at the main Kalamazoo campus, while the College of Aviation and flight line are at W.K. Kellogg Airport in Battle Creek, about 25 miles away.",
    climate: "Four seasons with cloudy, snowy winters and pleasant summers; broad weather exposure.",
    aviation: "B.S. Aviation Flight Science with Part 141 training at W.K. Kellogg Airport in Battle Creek.",
    ratp: "Yes — qualifying degree/coursework supports reduced-hour R-ATP", fleet: "32 Cirrus SR20 Gen 7, 9 Piper Seminoles, plus specialty aircraft and modern training devices (published inventory).",
    partners: "Delta and other airline/industry relationships and internships.",
    cost: "Public-university tuition; residency matters.", flightCost: "2024–25 published private-through-commercial flight lab estimate was about $81,049, before electives.",
    xc: "MAC Division I program. Strong varsity marks may open a conversation, but roster needs control access.",
    times: { scholarship: "4:13 / 9:04", recruit: "4:22 / 9:26", walkon: "4:31 / 9:48" },
    pros: ["Modern, clearly published fleet", "Established aviation college", "DI mid-major athletics"],
    cons: ["Flight campus commute from Kalamazoo", "Winter weather", "High flight-lab total beyond tuition"],
    notes: "A strong all-around contender; evaluate the daily transportation and practice-to-flight logistics carefully.",
    scores: { aviation: 9, athletics: 8, value: 7, climate: 5, campus: 8 },
    sources: [{ label: "Flight Science", url: "https://wmich.edu/aviation/academics/aviation-flight-science" }, { label: "Flight fees", url: "https://files.wmich.edu/s3fs-public/2024-09/2024-2025_flight_fees_1.pdf" }, { label: "Men's XC", url: "https://wmubroncos.com/sports/mens-cross-country" }]
  },
  {
    id:"bgsu",name:"Bowling Green State University",short:"BGSU",location:"Bowling Green, Ohio",state:"OH",division:"NCAA Division I",conference:"Mid-American Conference",setting:"Mid-sized public university in a classic college town",size:"About 19,000 students across the university; the main Bowling Green campus has the traditional residential experience.",flightLocation:"The university-owned Wood County Regional Airport and Bowling Green Flight Center are on the main campus, making this one of the easiest flight-to-practice arrangements.",climate:"Four seasons with cold, windy winters and warm, humid summers.",aviation:"B.S. in Aviation with a Flight Technology and Operations specialization; AABI-accredited Part 141 training.",ratp:"Yes — 1,000 hours with 60 approved credits or 1,250 hours with 30 credits",fleet:"Modern university flight-center aircraft and simulators; confirm the current fleet and dispatch rate.",partners:"Airline and industry relationships change; ask about active cadet pathways during the aviation tour.",cost:"Public-university tuition with an Ohio-resident advantage.",flightCost:"Flight-course fees are additional; request a current private-through-CFI completion estimate.",xc:"MAC Division I program with serious but more approachable standards than Power-conference teams.",times:{scholarship:"4:13 / 9:04",recruit:"4:22 / 9:26",walkon:"4:32 / 9:50"},pros:["Airport on the main campus","1,000-hour R-ATP route","Mid-major DI opportunity"],cons:["Cold and windy winters","Selective aviation capacity","DI roster space changes yearly"],notes:"A particularly clean aviation-and-athletics match because the airport, classrooms and team are based together.",scores:{aviation:9,athletics:8,value:8,climate:5,campus:9},sources:[{label:"Aviation",url:"https://www.bgsu.edu/engineering-and-innovation/schools-and-departments/aviation.html"},{label:"R-ATP",url:"https://www.bgsu.edu/engineering-and-innovation/schools-and-departments/aviation/about/r-atp"},{label:"Men's XC",url:"https://bgsufalcons.com/sports/mens-cross-country"}]
  },
  {
    id:"central-washington",name:"Central Washington University",short:"CWU",location:"Ellensburg, Washington",state:"WA",division:"NCAA Division II",conference:"Great Northwest Athletic Conference",setting:"Mid-sized public university in a small mountain-region college town",size:"About 10,000 students, offering a medium-sized campus with a strong regional identity.",flightLocation:"Academic classes and the Flight Training Center are in Ellensburg; the airport facility is a short trip from the main campus rather than a distant satellite.",climate:"Dry, sunny summers; cold winters, wind and occasional snow in central Washington.",aviation:"B.S. Professional Pilot with integrated aircraft and simulator instruction.",ratp:"Yes — qualifying graduates may pursue the 1,000-hour R-ATP route",fleet:"University aircraft, simulators and a dedicated Flight Training Center at Bowers Field.",partners:"Regional-airline recruiting and internship relationships; verify the current pathway roster.",cost:"Public tuition with different resident and nonresident rates.",flightCost:"Published 2026–27 flight-training fees are separate from tuition and vary by progress.",xc:"GNAC Division II program that can be a realistic target for a strong high-school varsity runner.",times:{scholarship:"4:19 / 9:20",recruit:"4:29 / 9:45",walkon:"4:43 / 10:10"},pros:["DII recruiting fit","Dry climate and mountain access","Established 1,000-hour R-ATP program"],cons:["Cold and windy winter flying","Limited annual pilot intake","Travel distance from major cities"],notes:"A strong western DII option with an established professional-pilot degree and manageable campus-to-airport logistics.",scores:{aviation:9,athletics:7,value:8,climate:7,campus:8},sources:[{label:"Professional Pilot",url:"https://www.cwu.edu/academics/aviation/bs-professional-pilot/"},{label:"Men's XC",url:"https://wildcatsports.com/sports/cross-country"}]
  },
  {
    id:"delaware-state",name:"Delaware State University",short:"DSU",location:"Dover, Delaware",state:"DE",division:"NCAA Division I",conference:"Mid-Eastern Athletic Conference",setting:"Public HBCU in Delaware's capital city",size:"About 6,500 students, giving it a smaller Division I campus environment.",flightLocation:"Aviation academics are based at the main Dover campus, with university flight operations at nearby Delaware Airpark.",climate:"Four seasons, humid summers and cool winters with generally moderate coastal weather.",aviation:"B.S. Aviation, Professional Pilot concentration, with university-operated flight training through commercial, multi-engine and instructor preparation.",ratp:"Yes — qualifying Professional Pilot graduates are R-ATP eligible",fleet:"University flight-school aircraft and simulators; confirm current types and student-to-aircraft ratio.",partners:"United Aviate and Atlas Air pathways are among its published relationships.",cost:"Public HBCU pricing; residency and aid materially affect net cost.",flightCost:"Flight charges are separate from tuition; request the current full-program budget.",xc:"MEAC Division I program with a smaller roster and a potentially broader recruiting window than major conferences.",times:{scholarship:"4:17 / 9:15",recruit:"4:27 / 9:40",walkon:"4:40 / 10:05"},pros:["University-based flight school","United Aviate pathway","Smaller DI environment"],cons:["Separate airport transportation","Humid summers","Confirm current fleet capacity"],notes:"An overlooked East Coast option combining an HBCU experience, university flight training and Division I running.",scores:{aviation:8,athletics:7,value:8,climate:7,campus:7},sources:[{label:"Aviation",url:"https://business.desu.edu/departments/aviation"},{label:"United Aviate",url:"https://www.desu.edu/news/2023/11/dsu-united-airlines-sign-aviate-program-agreement"},{label:"Men's XC",url:"https://dsuhornets.com/sports/mens-cross-country"}]
  },
  {
    id:"eku",name:"Eastern Kentucky University",short:"EKU",location:"Richmond, Kentucky",state:"KY",division:"NCAA Division I",conference:"Atlantic Sun Conference",setting:"Large regional public university in a small city south of Lexington",size:"About 15,000 students, with a traditional residential main campus.",flightLocation:"Classes are on the Richmond campus; flying is based at Central Kentucky Regional Airport, a short drive away, where a new training center is planned for completion in 2027.",climate:"Four seasons, humid summers, mild-to-cool winters and occasional storms.",aviation:"B.S. Aviation, Professional Flight concentration; Kentucky's collegiate Part 141 flight program.",ratp:"Yes — 1,000-hour R-ATP pathway for qualifying graduates",fleet:"Published fleet includes 27 Cessna singles, 3 Piper Seminoles and several simulators.",partners:"Republic RJet and Allegiant Accelerate are published pilot pathways.",cost:"Public-university tuition with resident and regional discounts where applicable.",flightCost:"Flight laboratory fees are additional; obtain a current completion estimate.",xc:"Historically strong Division I distance program; recruiting expectations can be demanding.",times:{scholarship:"4:11 / 9:00",recruit:"4:20 / 9:20",walkon:"4:30 / 9:42"},pros:["Deep distance-running tradition","Large published fleet","1,000-hour R-ATP and airline pathways"],cons:["Competitive DI roster","Airport commute","Program demand may affect flight scheduling"],notes:"One of the strongest newly identified combinations, especially for a runner already near Division I recruiting level.",scores:{aviation:9,athletics:9,value:8,climate:7,campus:8},sources:[{label:"Aviation B.S.",url:"https://www.eku.edu/jsms/aviation/bs-aviation/"},{label:"Fleet",url:"https://www.eku.edu/jsms/aviation/"},{label:"Men's XC",url:"https://ekusports.com/sports/cross-country"}]
  },
  {
    id:"hampton",name:"Hampton University",short:"HU",location:"Hampton, Virginia",state:"VA",division:"NCAA Division I",conference:"Coastal Athletic Association",setting:"Private HBCU on a historic waterfront campus",size:"About 3,500 students, creating a smaller and more personal Division I environment.",flightLocation:"Academic classes are on the main Hampton campus. Rick Aviation provides Part 141 flight training at Newport News/Williamsburg International Airport about 15 minutes away; weekday transportation is provided.",climate:"Mild winters, hot humid summers and coastal storm or hurricane exposure.",aviation:"B.S. Flight Education/Professional Flight leading through private, instrument, commercial and CFI certificates.",ratp:"Confirm the exact current R-ATP credit pathway with Hampton before enrolling",fleet:"Training is delivered by partner Rick Aviation rather than a university-owned fleet.",partners:"Graduates work across major, cargo and regional airlines; ask about current formal pipeline agreements.",cost:"Private-university tuition; institutional aid can materially change net price.",flightCost:"Current published flight-lab fees total roughly the mid-$60,000s and are paid in addition to tuition.",xc:"CAA Division I program in a smaller-school setting; roster needs should be discussed directly with the coach.",times:{scholarship:"4:16 / 9:12",recruit:"4:26 / 9:36",walkon:"4:38 / 10:00"},pros:["Historic HBCU experience","Transportation to partner airport","Smaller DI campus"],cons:["Partner-operated flight training","Private tuition plus flight fees","Coastal weather disruptions"],notes:"A distinctive HBCU option with a true Professional Flight degree and a manageable 15-minute airport arrangement.",scores:{aviation:8,athletics:7,value:6,climate:8,campus:8},sources:[{label:"Flight Education",url:"https://home.hamptonu.edu/engineering/aviation-flight-education/"},{label:"Flight FAQ",url:"https://home.hamptonu.edu/engineering/aviation-faq/"},{label:"Men's XC",url:"https://hamptonpirates.com/sports/mens-cross-country"}]
  },
  {
    id:"hesston",name:"Hesston College",short:"HC",location:"Hesston / Newton, Kansas",state:"KS",division:"NAIA",conference:"Continental Athletic Conference",setting:"Very small Mennonite college in a rural Kansas community",size:"A very small college with under 1,000 students and a close-knit campus atmosphere.",flightLocation:"Academic life is based in Hesston; aviation facilities are at Newton City-County Airport, requiring a regular short drive.",climate:"Hot, windy summers; cold winters and frequent Great Plains wind exposure.",aviation:"B.S. Aviation—Professional Pilot with private, instrument, commercial, multi-engine, CFI and CFII preparation.",ratp:"Yes — qualifying graduates may apply at 1,000 hours",fleet:"Modern Piper Archer aircraft and flight simulation equipment.",partners:"SkyWest Airlines Partner School and other industry connections.",cost:"Small private-college pricing; compare grants and scholarships carefully.",flightCost:"Flight training is additional; request the current four-year course-fee plan.",xc:"Newer NAIA program with a broader entry window than established NCAA teams.",times:{scholarship:"4:30 / 9:50",recruit:"4:45 / 10:20",walkon:"5:00 / 10:50"},pros:["1,000-hour R-ATP","Potentially accessible NAIA roster","Small classes and close support"],cons:["Very small campus and town","Airport commute","Newer four-year and NAIA model"],notes:"A promising likely-level option for a developing runner who wants personal attention and a direct professional-pilot path.",scores:{aviation:8,athletics:6,value:7,climate:5,campus:6},sources:[{label:"Professional Pilot",url:"https://hesston.edu/academics/programs/aviation-pilot-b.s/"},{label:"NAIA membership",url:"https://hesston.edu/about/news/article/hesston-college-joins-naia-and-nccaa-for-2025-26-athletic-season/"},{label:"Men's XC",url:"https://hclarks.com/sports/mens-cross-country"}]
  },
  {
    id:"lewis",name:"Lewis University",short:"Lewis",location:"Romeoville, Illinois",state:"IL",division:"NCAA Division II",conference:"Great Lakes Valley Conference",setting:"Private university in suburban Chicago",size:"About 6,500 students, combining a smaller campus with access to the Chicago aviation market.",flightLocation:"Lewis University Airport is directly beside the main campus, creating an unusually convenient flight-training setup.",climate:"Four seasons, cold winters, humid summers and variable Midwest weather.",aviation:"B.S. Aviation Flight Technology with Part 141 and Part 61 university flight training.",ratp:"Yes — qualifying graduates can pursue reduced-hour R-ATP; confirm whether the student's plan yields 1,000 or 1,250 hours",fleet:"University training aircraft, simulators and on-campus airport facilities.",partners:"Chicago-area industry access and airline recruiting connections.",cost:"Private-university tuition; merit aid may reduce the academic price.",flightCost:"Flight laboratory fees are additional and should be priced course by course.",xc:"GLVC Division II program and a realistic target for many strong varsity runners.",times:{scholarship:"4:19 / 9:20",recruit:"4:30 / 9:47",walkon:"4:44 / 10:12"},pros:["Airport beside campus","DII recruiting fit","Chicago aviation-market access"],cons:["Private tuition plus flight fees","Winter disruptions","Confirm precise R-ATP credit route"],notes:"One of the most practical DII additions because the team, university and airport are all closely connected.",scores:{aviation:8,athletics:7,value:6,climate:5,campus:8},sources:[{label:"Flight Technology",url:"https://www.lewisu.edu/academics/aviation/flight-management/"},{label:"Men's XC",url:"https://lewisflyers.com/sports/mens-cross-country"}]
  },
  {
    id:"liberty",name:"Liberty University",short:"LU",location:"Lynchburg, Virginia",state:"VA",division:"NCAA Division I",conference:"Conference USA",setting:"Large private Christian university in the Blue Ridge foothills",size:"About 16,000 residential students, separate from Liberty's much larger online enrollment.",flightLocation:"Aviation academics are on the Lynchburg campus; university flight operations use nearby Lynchburg Regional Airport.",climate:"Four seasons with warm humid summers, cool winters and nearby hills and trails.",aviation:"B.S. Aeronautics, Commercial/Corporate concentration, with structured collegiate flight training.",ratp:"Yes — qualifying School of Aeronautics graduates may pursue reduced-hour R-ATP",fleet:"Large university flight operation with aircraft and simulators; confirm current inventory and dispatch performance.",partners:"Multiple airline pathway and cadet relationships through the School of Aeronautics.",cost:"Private tuition with substantial institutional-aid possibilities.",flightCost:"Flight fees are additional; request a current zero-time completion projection.",xc:"Competitive Division I program; strong marks are required for serious consideration.",times:{scholarship:"4:10 / 8:58",recruit:"4:19 / 9:18",walkon:"4:29 / 9:40"},pros:["Large aviation school","DI athletics and strong facilities","Blue Ridge running terrain"],cons:["Competitive running and flight admission","Private cost","Distinctly Christian campus expectations"],notes:"A serious option for a student who wants a faith-centered campus and is already competitive at the Division I level.",scores:{aviation:9,athletics:9,value:7,climate:8,campus:9},sources:[{label:"School of Aeronautics",url:"https://www.liberty.edu/aeronautics/"},{label:"Men's XC",url:"https://libertyflames.com/sports/cross-country"}]
  },
  {
    id:"morningside",name:"Morningside University",short:"MSide",location:"Sioux City, Iowa",state:"IA",division:"NAIA",conference:"Great Plains Athletic Conference",setting:"Small private university in a regional Midwestern city",size:"About 2,000 students, with a close residential campus environment.",flightLocation:"Classes are based on Morningside's main campus; Part 141 flight training is conducted at Sioux Gateway Airport with Oracle Aviation.",climate:"Hot summers, cold windy winters and broad Great Plains weather experience.",aviation:"B.S. Professional Flight with private, instrument, commercial and CFI or multi-engine training.",ratp:"Confirm current FAA R-ATP authorization; the program is newer and Part 141 status alone does not guarantee reduced hours",fleet:"Training uses Cessna 172 or comparable aircraft through Oracle Aviation.",partners:"Students interact with regional aviation employers and airport professionals.",cost:"Private-university tuition with academic and athletic aid possibilities.",flightCost:"Published 2026–27 core rating fees total about $60,000 with CFI or about $63,000 with multi-engine, before extra hours.",xc:"Established GPAC NAIA team with more recruiting and scholarship flexibility than most NCAA DI programs.",times:{scholarship:"4:25 / 9:35",recruit:"4:38 / 10:05",walkon:"4:52 / 10:35"},pros:["NAIA aid flexibility","Clearly published flight fees","Small campus and regional airport access"],cons:["R-ATP needs confirmation","Cold and windy winters","Partner-operated training"],notes:"A useful NAIA target where a solid varsity runner may find both roster opportunity and aviation training.",scores:{aviation:7,athletics:7,value:7,climate:4,campus:7},sources:[{label:"Professional Flight",url:"https://www.morningside.edu/professional-flight-at-mside"},{label:"Men's XC",url:"https://msidemustangs.com/sports/mens-cross-country"}]
  },
  {
    id:"ohio",name:"Ohio University",short:"OHIO",location:"Athens, Ohio",state:"OH",division:"NCAA Division I",conference:"Mid-American Conference",setting:"Large public university in a scenic Appalachian college town",size:"About 21,000 students on the Athens campus, with additional students across the university system.",flightLocation:"Ohio University owns and operates Gordon K. Bush Airport near Athens; aviation and varsity athletics are part of the same main-campus university.",climate:"Four seasons, wooded hills, humid summers and cool-to-cold winters.",aviation:"B.S. Aviation Flight with first-year flying through the university's FAA-approved Part 141 program.",ratp:"Yes — 1,000 hours for Aviation Flight graduates; 1,250 for the associate pathway",fleet:"University-owned aircraft including six new Cirrus SR20s added in 2025, plus simulators.",partners:"Strong alumni presence across airlines, corporate aviation and NetJets.",cost:"Public tuition with an Ohio-resident advantage.",flightCost:"Flight-course charges are additional; the selective 2026–27 major may use a waitlist.",xc:"MAC Division I program that finished fifth at the 2025 conference meet; serious mid-major marks are needed.",times:{scholarship:"4:13 / 9:04",recruit:"4:22 / 9:26",walkon:"4:32 / 9:48"},pros:["University-owned airport","1,000-hour R-ATP","Strong college-town and trail setting"],cons:["Selective aviation waitlist","DI roster competition","Winter weather"],notes:"A high-quality public option with excellent campus fit; apply early because Aviation Flight capacity is limited.",scores:{aviation:9,athletics:8,value:8,climate:6,campus:9},sources:[{label:"Aviation",url:"https://www.ohio.edu/engineering/aviation/undergraduate"},{label:"Waitlist",url:"https://www.ohio.edu/admissions/apply/aviation-wait-list"},{label:"Men's XC",url:"https://ohiobobcats.com/sports/mcross"}]
  },
  {
    id:"ohio-state",name:"The Ohio State University",short:"OSU",location:"Columbus, Ohio",state:"OH",division:"NCAA Division I",conference:"Big Ten Conference",setting:"Very large flagship university in a major city",size:"More than 60,000 students at the Columbus campus, offering major research-university scale.",flightLocation:"Professional Pilot students train at the university-owned Ohio State University Airport in northwest Columbus, a drive from the central campus.",climate:"Four seasons, humid summers and cold, cloudy winters.",aviation:"B.S. Aviation or Air Transportation major with the competitive Professional Pilot Certification specialization.",ratp:"Yes — 1,000 hours with 60 approved credits or 1,250 with 30–59",fleet:"University aircraft, flight labs and advanced simulators at Ohio State University Airport.",partners:"ATSG cargo-pilot pathway and other industry relationships.",cost:"Public flagship tuition; nonresident pricing and Columbus housing raise total cost.",flightCost:"Ohio State publishes average flight-program costs around $73,600–$76,400 beyond tuition, depending on the option.",xc:"Big Ten distance program; among the most difficult rosters in this directory to join.",times:{scholarship:"4:06 / 8:52",recruit:"4:13 / 9:06",walkon:"4:20 / 9:22"},pros:["Elite university resources","University-owned airport","1,000-hour R-ATP"],cons:["Extremely competitive XC roster","Competitive flight-specialization admission","Large campus and airport commute"],notes:"Treat as a reach for both running and flight admission, but it is a legitimate elite-university combination.",scores:{aviation:9,athletics:10,value:8,climate:5,campus:10},sources:[{label:"Flight Lab",url:"https://fly.osu.edu/academic-training-programs/academic-flight-lab"},{label:"R-ATP",url:"https://aviation.osu.edu/students/alumni/restricted-atp"},{label:"Men's XC",url:"https://ohiostatebuckeyes.com/sports/mens-cross-country"}]
  },
  {
    id:"oklahoma",name:"University of Oklahoma",short:"OU",location:"Norman, Oklahoma",state:"OK",division:"NCAA Division I",conference:"Southeastern Conference",setting:"Large flagship university in a major college town",size:"About 30,000 students across the university, with a large residential Norman campus.",flightLocation:"The School of Aviation and Max Westheimer Airport are in Norman near the main campus; this is not merely an off-site third-party degree.",climate:"Hot, windy summers, mild winters and significant thunderstorm and severe-weather exposure.",aviation:"B.S. Aviation with a Professional Pilot concentration and university flight training.",ratp:"Yes — qualifying graduates may pursue reduced-hour R-ATP; confirm the approved credit track",fleet:"University flight aircraft and simulators at Max Westheimer Airport.",partners:"Published airline and industry relationships vary; ask about active pathway eligibility.",cost:"Public flagship pricing with an Oklahoma-resident advantage.",flightCost:"Course flight fees are additional and should be compared using a four-year estimate.",xc:"Varsity NCAA Division I men's cross country—not a club team. SEC-level resources make the roster competitive.",times:{scholarship:"4:08 / 8:55",recruit:"4:16 / 9:12",walkon:"4:24 / 9:30"},pros:["Main-university flight program","Major-college campus and SEC resources","Warm-weather training"],cons:["Competitive DI roster","Severe-weather disruptions","Large-program scheduling demands"],notes:"This corrects the earlier club-team error: Oklahoma is a legitimate varsity DI aviation-and-XC option.",scores:{aviation:9,athletics:9,value:8,climate:7,campus:9},sources:[{label:"School of Aviation",url:"https://www.ou.edu/ags/aviation"},{label:"Men's XC",url:"https://soonersports.com/sports/cross-country"}]
  },
  {
    id:"oklahoma-state",name:"Oklahoma State University",short:"OSU",location:"Stillwater, Oklahoma",state:"OK",division:"NCAA Division I",conference:"Big 12 Conference",setting:"Large public university in a traditional college town",size:"About 26,000 students at the Stillwater campus.",flightLocation:"Professional Pilot academics and OSU Flight Center operations are in Stillwater close to the main campus.",climate:"Hot, windy summers, cool winters and frequent Plains thunderstorms.",aviation:"B.S. Aerospace Administration and Operations, Professional Pilot option, including CFI preparation.",ratp:"Yes — FAA-authorized qualifying degree and course pathway",fleet:"University flight-center aircraft and simulators; confirm the latest fleet count.",partners:"Airline recruiting and cadet relationships through OSU aviation.",cost:"Public tuition with favorable Oklahoma-resident pricing.",flightCost:"Flight-course fees are additional; request a rating-by-rating estimate.",xc:"National-championship-caliber Big 12 men's distance program; exceptionally difficult roster access.",times:{scholarship:"4:03 / 8:45",recruit:"4:10 / 8:58",walkon:"4:17 / 9:15"},pros:["Excellent professional-pilot program","Flight center near campus","Nationally elite distance culture"],cons:["One of the hardest teams to make","Flight capacity and high combined workload","Wind and severe weather"],notes:"Outstanding on paper, but only a sensible athletic target for a truly elite national-level runner.",scores:{aviation:9,athletics:10,value:8,climate:7,campus:9},sources:[{label:"Professional Pilot",url:"https://go.okstate.edu/undergraduate-academics/majors/professional-pilot-option"},{label:"R-ATP",url:"https://education.okstate.edu/departments-programs/educational-foundations-leadership-aviation/flight-center/restricted-atp"},{label:"Men's XC",url:"https://okstate.com/sports/mxct"}]
  },
  {
    id:"rocky-mountain",name:"Rocky Mountain College",short:"RMC",location:"Billings, Montana",state:"MT",division:"NAIA",conference:"Frontier Conference",setting:"Small private college in Montana's largest city near mountain recreation",size:"About 1,000 students, offering a highly personal campus experience.",flightLocation:"Aviation academics are on the Billings campus, with college flight operations at nearby Billings Logan International Airport.",climate:"Dry climate, cold winters, warm summers, wind and mountain-weather exposure.",aviation:"AABI-accredited B.S. Aeronautical Science—Professional Pilot using college-owned aircraft.",ratp:"Confirm the current FAA-approved R-ATP credit level directly with the program",fleet:"College-owned Piper and Cessna aircraft, glass cockpits, simulators and CRJ systems training.",partners:"Delta Propel affiliate; graduates also enter SkyWest, Horizon, Republic and other operators.",cost:"Small private-college tuition; academic and athletic aid may substantially change net price.",flightCost:"Flight fees are separate and proficiency-dependent; request a current completion budget.",xc:"Competitive Frontier Conference NAIA program with recent national-championship participation.",times:{scholarship:"4:20 / 9:25",recruit:"4:33 / 9:55",walkon:"4:48 / 10:25"},pros:["NAIA athletic-aid flexibility","College-owned aircraft and AABI accreditation","Delta Propel and mountain setting"],cons:["Small enrollment","Cold and windy winters","R-ATP details need direct confirmation"],notes:"One of the strongest NAIA additions, especially for a runner seeking a small school and western outdoor lifestyle.",scores:{aviation:9,athletics:8,value:7,climate:6,campus:8},sources:[{label:"Aeronautical Science",url:"https://rocky.edu/academics/academic-programs/aviation/areas-in-aviation/aeronautical-science/"},{label:"Career pathways",url:"https://rocky.edu/academics/academic-programs/aviation/explore-careers/"},{label:"Men's XC",url:"https://gobattlinbears.com/sports/mens-cross-country"}]
  },
  {
    id:"saint-louis",name:"Saint Louis University",short:"SLU",location:"St. Louis, Missouri",state:"MO",division:"NCAA Division I",conference:"Atlantic 10 Conference",setting:"Private Jesuit research university in a major city",size:"About 15,000 students across undergraduate and graduate programs.",flightLocation:"Main-campus academics are in St. Louis; flight training is conducted at St. Louis Downtown Airport in Cahokia Heights, Illinois, requiring regular transportation.",climate:"Hot humid summers, cool winters and four-season Midwest weather.",aviation:"B.S. Aeronautics, Flight Science concentration; Part 141 program with private through commercial multi-engine and CFI training.",ratp:"Yes — 1,000 or 1,250 hours depending on approved credits",fleet:"Diamond DA20s, Piper Archers with G1000 NXi, Piper Seminoles and a Boeing 737 MAX simulator.",partners:"Envoy, Republic and Mesa pathways are published.",cost:"Private Jesuit-university pricing with merit and need-based aid.",flightCost:"The current Flight Science sequence publishes about $77,400 in added flight fees.",xc:"Atlantic 10 Division I program; strong regional marks are needed for roster consideration.",times:{scholarship:"4:13 / 9:05",recruit:"4:22 / 9:28",walkon:"4:33 / 9:50"},pros:["Long aviation history","Modern published fleet","Urban internships and 1,000-hour R-ATP"],cons:["Private tuition plus flight fees","Airport across the river from campus","Flight-slot capacity can be limited"],notes:"A strong urban aviation option, but applicants must secure a flight slot and plan the airport commute carefully.",scores:{aviation:9,athletics:8,value:6,climate:6,campus:8},sources:[{label:"Flight Science",url:"https://www.slu.edu/science-and-engineering/academics/undergraduate-programs/aeronautics-bs.php"},{label:"Flight School",url:"https://www.slu.edu/science-and-engineering/academics/parks-aviation-science/flight-school/"},{label:"Men's XC",url:"https://slubillikens.com/sports/cross-country"}]
  },
  {
    id:"san-jose-state",name:"San José State University",short:"SJSU",location:"San José, California",state:"CA",division:"NCAA Division I",conference:"Mountain West Conference",setting:"Large urban public university in Silicon Valley",size:"About 36,000 students in a dense downtown campus environment.",flightLocation:"Aviation classes are at the main San José campus. Flight ratings are earned through affiliated schools at Reid-Hillview Airport, typically 30–45 minutes each way by car depending on traffic.",climate:"Mild, dry summers and rainy winters with generally excellent year-round flying weather.",aviation:"B.S. Aviation, Professional Flight option, combining university coursework with affiliated FAA-approved flight schools.",ratp:"Yes — qualifying degree and approved partner training may lead to R-ATP; every required course and provider must be verified",fleet:"Aircraft belong to affiliated flight schools rather than SJSU; availability varies by provider.",partners:"Silicon Valley and Bay Area aviation access; confirm current formal airline pathways.",cost:"California public tuition, but Bay Area housing and transportation are expensive.",flightCost:"Flight costs are paid directly to the partner school in addition to tuition.",xc:"Mountain West Division I program; strong marks and coach approval are required.",times:{scholarship:"4:10 / 9:00",recruit:"4:19 / 9:20",walkon:"4:29 / 9:42"},pros:["Excellent flying climate","Major aviation market","Public-university degree and R-ATP option"],cons:["High housing costs","Traffic-heavy partner-airport commute","No university-owned fleet"],notes:"A valid but logistics-heavy option; the student must budget both Bay Area living costs and substantial weekly travel time.",scores:{aviation:8,athletics:8,value:6,climate:10,campus:7},sources:[{label:"Professional Flight",url:"https://www.sjsu.edu/avtech/programs/bs-aviation/bs-professional-flight.php"},{label:"Men's XC",url:"https://sjsuspartans.com/sports/mens-cross-country"}]
  },
  {
    id:"southeastern-oklahoma",name:"Southeastern Oklahoma State University",short:"SEOSU",location:"Durant, Oklahoma",state:"OK",division:"NCAA Division II",conference:"Great American Conference",setting:"Small public university in a rural regional city near North Texas",size:"About 5,000 students, with a small-campus atmosphere.",flightLocation:"Professional Pilot classes and flight operations are based in Durant close to the main university.",climate:"Hot humid summers, mild winters and thunderstorm or severe-weather exposure.",aviation:"B.S. Aviation, Professional Pilot program with structured university flight training.",ratp:"Yes — qualifying graduates can pursue the 1,000-hour R-ATP route",fleet:"University aviation aircraft and simulators; confirm the current inventory and flight-slot wait.",partners:"Southwest Destination 225° and other industry relationships have been published.",cost:"Public regional-university pricing with strong value potential.",flightCost:"Flight fees are separate; the selective program requires its own application and FAA first-class medical.",xc:"Great American Conference DII program with potentially accessible recruiting standards.",times:{scholarship:"4:22 / 9:30",recruit:"4:35 / 10:00",walkon:"4:50 / 10:30"},pros:["1,000-hour R-ATP","Potentially strong value","DII roster accessibility"],cons:["Small-town setting","Separate selective pilot application","Heat and severe weather"],notes:"A useful value-oriented target for a developing runner, provided he earns admission to the limited Professional Pilot class.",scores:{aviation:8,athletics:6,value:9,climate:6,campus:6},sources:[{label:"Professional Pilot",url:"https://www.se.edu/aerospace/professional-pilot-application/"},{label:"Men's XC",url:"https://gosoutheastern.com/sports/mens-cross-country"}]
  },
  {
    id:"southern-utah",name:"Southern Utah University",short:"SUU",location:"Cedar City, Utah",state:"UT",division:"NCAA Division I",conference:"Western Athletic Conference",setting:"Mid-sized public university in a high-desert town near national parks",size:"About 15,000 students, with a growing campus and strong outdoor culture.",flightLocation:"The Professional Pilot program is based in Cedar City, with on-campus aviation support and flight operations at nearby Cedar City Regional Airport.",climate:"Dry high-desert climate, four seasons, sunny skies, altitude and occasional winter snow.",aviation:"Professional Pilot program with fixed-wing and rotor-wing pathways; university-provided flight training.",ratp:"Confirm the current fixed-wing FAA R-ATP authorization and approved credit level",fleet:"Fixed-wing and helicopter training fleets plus simulators; confirm current aircraft mix.",partners:"Industry partnerships and strong western aviation employment connections.",cost:"Public tuition with Utah-resident and nonresident differences.",flightCost:"Flight fees are substantial and separate; fixed-wing and rotor-wing totals differ greatly.",xc:"Competitive WAC Division I distance program with altitude-training benefits.",times:{scholarship:"4:12 / 9:02",recruit:"4:21 / 9:24",walkon:"4:31 / 9:46"},pros:["High-altitude training","Excellent outdoor setting","Fixed-wing and helicopter options"],cons:["DI roster competition","R-ATP details need confirmation","Winter and density-altitude operations"],notes:"A compelling western option for a strong runner who values altitude, public-school pricing and outdoor access.",scores:{aviation:8,athletics:8,value:8,climate:9,campus:8},sources:[{label:"Fixed Wing",url:"https://www.suu.edu/aviation/fixed-wing.html"},{label:"Men's XC",url:"https://suutbirds.com/sports/mens-cross-country"}]
  },
  {
    id:"ucm",name:"University of Central Missouri",short:"UCM",location:"Warrensburg, Missouri",state:"MO",division:"NCAA Division II",conference:"Mid-America Intercollegiate Athletics Association",setting:"Mid-sized public university in a small Missouri college town",size:"About 13,000 students across undergraduate and graduate programs.",flightLocation:"Aviation academics are on the Warrensburg campus; flight operations use nearby Skyhaven Airport, which is university-owned.",climate:"Four seasons, humid summers, cold winters and thunderstorms.",aviation:"B.S. Professional Pilot leading to commercial single- and multi-engine and CFI qualifications.",ratp:"Yes — 1,000 hours with 60 approved credits or 1,250 with 30",fleet:"More than 20 Cessna 172s plus additional aircraft, training devices and a Boeing 737-800 simulator.",partners:"Envoy, GoJet and Republic pathway programs are published.",cost:"Public regional-university pricing with good value potential.",flightCost:"Flight fees are additional; request a completion estimate including repeats and checkrides.",xc:"Strong MIAA Division II program—competitive, but more reachable than major DI teams.",times:{scholarship:"4:17 / 9:15",recruit:"4:27 / 9:40",walkon:"4:40 / 10:05"},pros:["University-owned airport","Large training fleet","DII fit and strong value"],cons:["Small-town setting","Midwest weather","Flight fees beyond tuition"],notes:"One of the best newly found balance schools for aviation depth, cost and attainable high-level DII running.",scores:{aviation:9,athletics:8,value:9,climate:6,campus:8},sources:[{label:"Professional Pilot",url:"https://www.ucmo.edu/academics/programs/majors/hcbps/aviation/professional-pilot-bs/"},{label:"Program details",url:"https://www.ucmo.edu/academics/programs/majors/hcbps/aviation/professional-pilot-bs/professional-pilot-bs-additional-information/"},{label:"Men's XC",url:"https://ucmathletics.com/sports/mens-cross-country"}]
  },
  {
    id:"dubuque",name:"University of Dubuque",short:"UD",location:"Dubuque, Iowa",state:"IA",division:"NCAA Division III",conference:"American Rivers Conference",setting:"Small private university in a Mississippi River city",size:"About 2,000 students, offering a small and personal campus.",flightLocation:"Classes are on the main campus; flight operations are at Dubuque Regional Airport, requiring a regular drive.",climate:"Four seasons with cold snowy winters and warm humid summers.",aviation:"B.S. Flight Operations preparing students for professional flight careers and advanced certificates.",ratp:"Yes — qualifying students may use UD's R-ATP pathway",fleet:"University aviation aircraft and training facilities at Dubuque Regional Airport.",partners:"Published agreements have included Endeavor/Delta, Cape Air, Envoy, SkyWest and GoJet.",cost:"Private tuition; Division III does not award athletic scholarships, though academic and need aid may be available.",flightCost:"Flight fees are additional and should be requested as a full certificate sequence.",xc:"NCAA Division III program with a broad recruiting range and no athletic scholarships.",times:{scholarship:"No athletic aid in DIII",recruit:"4:35 / 10:00",walkon:"4:55 / 10:40"},pros:["Accessible DIII roster","Established flight degree","Small classes"],cons:["No athletic scholarships","Cold winters","Airport commute and private cost"],notes:"A practical roster-access option where academic aid—not athletic scholarship money—must drive affordability.",scores:{aviation:8,athletics:6,value:6,climate:4,campus:7},sources:[{label:"Flight Operations",url:"https://dbq.edu/Academics/UndergraduatePrograms/Aviation/BSFlightOperations/"},{label:"Men's XC",url:"https://dbq.edu/Athletics/MensAthletics/CrossCountry/"}]
  },
  {
    id:"unk",name:"University of Nebraska at Kearney",short:"UNK",location:"Kearney, Nebraska",state:"NE",division:"NCAA Division II",conference:"Mid-America Intercollegiate Athletics Association",setting:"Mid-sized public university in a regional Great Plains city",size:"About 6,000 students, creating a smaller public-university experience.",flightLocation:"Aviation academics and the university's Part 141 pilot school are in Kearney, with airport training a short drive from campus.",climate:"Hot summers, cold windy winters and fast-changing Plains weather.",aviation:"B.S. Aviation Comprehensive with a Professional Pilot emphasis through commercial single- and multi-engine training.",ratp:"Yes — qualifying graduates may apply at 1,000 hours",fleet:"Part 141 university pilot-school aircraft and simulators; confirm current fleet and availability.",partners:"Regional airline and aviation-employer connections; current pathways should be verified.",cost:"Public pricing; UNK advertises an all-students in-state tuition initiative subject to current rules.",flightCost:"Flight fees are additional; the program is not approved for GI Bill Professional Pilot benefits.",xc:"MIAA Division II program with strong regional competition and attainable recruiting ranges for good varsity runners.",times:{scholarship:"4:19 / 9:22",recruit:"4:30 / 9:48",walkon:"4:44 / 10:12"},pros:["1,000-hour R-ATP","Small public campus","DII recruiting fit"],cons:["Wind and winter cold","No GI Bill approval for this emphasis","Smaller airline-network footprint"],notes:"A potentially excellent value target combining a 1,000-hour R-ATP route with realistic DII opportunity.",scores:{aviation:8,athletics:7,value:9,climate:4,campus:7},sources:[{label:"Aviation degree",url:"https://www.unk.edu/academics/itec/aviation/aviation-degree.php"},{label:"Men's XC",url:"https://lopers.com/sports/mens-cross-country"}]
  },
  {
    id:"utah-state",name:"Utah State University",short:"USU",location:"Logan, Utah",state:"UT",division:"NCAA Division I",conference:"Mountain West Conference",setting:"Large public university in a mountain valley college town",size:"About 29,000 students statewide, with the main residential and aviation experience centered in Logan.",flightLocation:"Aviation academics are on the Logan campus; flight operations are at nearby Logan-Cache Airport.",climate:"Four seasons, cold snowy winters, dry summers, altitude and mountain-valley inversions.",aviation:"B.S. Aviation Technology—Professional Pilot, Fixed Wing emphasis, including private, instrument, commercial, multi-engine and CFI.",ratp:"Yes — 1,000 hours with the degree, 60 approved credits and USU instrument/commercial training",fleet:"University flight-training aircraft and airport facilities; confirm current fleet inventory.",partners:"Horizon and other airline or internship relationships have been published.",cost:"Public tuition with Utah-resident and nonresident differences.",flightCost:"Special flight-class fees are added to tuition and include average training and checkride assumptions.",xc:"Strong Mountain West Division I program with altitude-training benefits and recent NCAA national participation.",times:{scholarship:"4:08 / 8:56",recruit:"4:16 / 9:12",walkon:"4:24 / 9:30"},pros:["1,000-hour R-ATP","Excellent mountain running environment","Integrated fixed-wing degree"],cons:["Very competitive XC team","Cold snowy winters","Winter inversions and flight delays"],notes:"One of the best western combinations, but the men's team requires near-elite Division I credentials.",scores:{aviation:9,athletics:9,value:8,climate:6,campus:9},sources:[{label:"Professional Pilot",url:"https://catalog.usu.edu/programs/ATPP-ATPP_FDWG_BS-MAJOR/program-overview-aoYks"},{label:"Men's XC",url:"https://utahstateaggies.com/sports/cross-country"}]
  }
].sort((a,b)=>a.name.localeCompare(b.name));

const timeInSeconds = (mark: string) => {
  const match = mark.match(/(\d+):(\d+)/);
  return match ? Number(match[1]) * 60 + Number(match[2]) : 9999;
};

const aviationRanking = [...schools].sort((a,b) =>
  b.scores.aviation - a.scores.aviation ||
  b.scores.campus - a.scores.campus ||
  b.scores.value - a.scores.value ||
  a.name.localeCompare(b.name)
);

const athleticsRanking = [...schools].sort((a,b) =>
  b.scores.athletics - a.scores.athletics ||
  timeInSeconds(a.times.scholarship) - timeInSeconds(b.times.scholarship) ||
  a.name.localeCompare(b.name)
);

export default function Home() {
  return <main>
    <header className="topbar" id="top"><div className="topbar-inner"><a className="brand" href="#top"><span className="brand-mark">R</span><span>Runway Routes</span></a><span className="top-label">College guide</span></div></header>

    <section className="intro"><div className="intro-copy"><p className="kicker">For runners who want to fly</p><h1>College cross country.<br/>Professional flight training.<br/><span>One school.</span></h1><p>This guide introduces {schools.length} colleges where a male student can study to become a professional pilot and compete in cross country. Read through the schools, talk with your family, and contact the flight program and coach before making a decision.</p><a className="primary-link" href="#schools">See the schools ↓</a></div><aside className="intro-card"><div className="plane-icon">✈</div><strong>What to compare</strong><ul><li>Can I realistically make the running team?</li><li>Can my family afford tuition and flight fees?</li><li>Will I enjoy the campus and weather?</li><li>Can flight lessons fit around practice and meets?</li></ul></aside></section>

    <section className="definitions"><div><span>Quick definitions</span><h2>Know the basics before you start.</h2></div><div className="definition-grid"><article><b>R-ATP</b><p>A Restricted Airline Transport Pilot certificate. An approved college program may let a graduate qualify for an airline first-officer job with fewer than the usual 1,500 flight hours—often 1,000 or 1,250.</p><p><strong>Why it matters:</strong> Requiring 250 or 500 fewer hours can shorten the time between college and airline eligibility and may reduce the cost of building those hours. It is not automatic: the student must complete the correct FAA-approved degree, courses and flight training.</p></article><article><b>Part 141</b><p>An FAA-approved flight-school structure with an organized curriculum and regular progress checks. It can make training more efficient, but each student still has to meet FAA standards.</p><p><strong>Why it matters:</strong> The structured program can help a student stay on schedule and may allow some certificates with fewer minimum flight hours than ordinary Part 61 training. For many college pilots, qualifying Part 141 coursework is also part of earning the R-ATP hour reduction.</p></article><article><b>Walk-on</b><p>A student who joins a college team without an athletic scholarship. A coach must still approve the roster spot, and space can change every year.</p></article><article><b>Recruit</b><p>An athlete a coach actively wants on the team. Recruiting interest does not always mean athletic scholarship money.</p></article><article><b>Main campus vs. satellite</b><p>A main-campus airport is on or beside the primary college. A nearby airport requires a short trip but is still part of the same program. A satellite aviation campus can require a longer daily commute, so transportation and practice timing matter.</p></article></div></section>

    <section className="recruit-note"><span>About the running times</span><p>Each profile shows estimated <b>1600m / 3200m</b> track times. These are planning ranges, not official standards or promises. Cross-country courses are different from one another, team needs change, and the coach makes the final decision. Always email the coach with verified race results.</p></section>

    <section className="rankings" id="rankings"><div className="ranking-heading"><p className="kicker">Two different rankings</p><h2>Strong flight school does not always mean strongest running team.</h2><p>These lists rank aviation and men's cross country independently. A high athletics ranking usually means a faster, harder-to-make roster—not necessarily a better personal recruiting fit.</p></div><div className="ai-caveat"><b>AI-generated planning rankings</b><p>These are independent, unofficial rankings created by AI from the researched information in this guide. They are not published by the universities, FAA, NCAA, NAIA, coaches or an accrediting organization. Programs can change, and reasonable people may rank them differently.</p></div><div className="ranking-grid">
      <article><header><span>✈</span><div><h3>Flight-program ranking</h3><p>Considers program depth, R-ATP pathway, fleet and simulators, Part 141 integration, airline connections, facilities, campus logistics and overall value.</p></div></header><ol>{aviationRanking.map((s,index)=><li key={s.id}><b>{index+1}</b><span>{s.name}<small>Aviation score: {s.scores.aviation}/10</small></span></li>)}</ol></article>
      <article><header><span>🏃</span><div><h3>Men's XC ranking</h3><p>Considers competitive level, conference strength, program resources, roster difficulty and the estimated recruiting marks used in this guide.</p></div></header><ol>{athleticsRanking.map((s,index)=><li key={s.id}><b>{index+1}</b><span>{s.name}<small>Athletics score: {s.scores.athletics}/10</small></span></li>)}</ol></article>
    </div></section>

    <section className="school-list" id="schools"><div className="list-heading"><p className="kicker">Alphabetical school list</p><h2>Explore all {schools.length} programs.</h2><p>Every card includes the same topics so the schools are easier to understand and compare.</p></div>
      {schools.map((s,index)=><article className="school-post" key={s.id}>
        <header className="post-header"><div className="avatar">{s.short.slice(0,3)}</div><div><p className="post-number">School {String(index+1).padStart(2,"0")} of {schools.length}</p><h3>{s.name}</h3><p className="post-meta">📍 {s.location} · {s.division} · {s.conference}</p></div></header>
        <p className="takeaway">{s.notes}</p>
        <div className="tag-row"><span>✈ Professional flight</span><span>🏃 Men's cross country</span><span>🎓 {s.ratp.startsWith("Yes") ? "R-ATP eligible" : "Confirm R-ATP"}</span></div>
        <div className="info-grid"><section><h4>Flight program</h4><p>{s.aviation}</p></section><section><h4>R-ATP path</h4><p>{s.ratp}</p></section><section><h4>School size</h4><p>{s.size}</p></section><section><h4>Where flight training happens</h4><p>{s.flightLocation}</p></section><section><h4>Aircraft and training</h4><p>{s.fleet}</p></section><section><h4>Airline connections</h4><p>{s.partners}</p></section><section><h4>Campus and weather</h4><p>{s.setting}. {s.climate}</p></section><section><h4>What could it cost?</h4><p>{s.cost} {s.flightCost}</p><p className="cost-timeframe"><b>Time frame:</b> Tuition, housing and cost-of-attendance figures are for one academic year unless the description specifically says four years. A flight figure labeled as a “total” covers the full published sequence of ratings—not one year. Other flight fees are charged by course and can be spread across several years.</p></section></div>
        <section className="running-box"><div><h4>Men's cross country</h4><p>{s.xc}</p></div><div className="times"><span><small>Scholarship-level estimate</small><b>{s.times.scholarship}</b></span><span><small>Recruit estimate</small><b>{s.times.recruit}</b></span><span><small>Walk-on conversation</small><b>{s.times.walkon}</b></span></div><p className="time-help">Times are shown as 1600m / 3200m. “Scholarship-level” means fast enough to potentially discuss athletic aid; it does not guarantee money.</p></section>
        <div className="pros-cons"><section><h4>👍 Reasons to consider it</h4><ul>{s.pros.map(x=><li key={x}>{x}</li>)}</ul></section><section><h4>⚠ Things to think about</h4><ul>{s.cons.map(x=><li key={x}>{x}</li>)}</ul></section></div>
        <footer className="post-footer"><span>Official links</span>{s.sources.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label} ↗</a>)}</footer>
      </article>)}
    </section>

    <section className="special-situations"><div className="special-heading"><p className="kicker">Technically possible, but complicated</p><h2>Special campus situations.</h2><p>These universities have both a professional-pilot path and men's cross country somewhere in the university system. They are not in the main directory because the flight program, team or degree arrangement could make daily participation impractical. A student should get written answers from both the coach and aviation program before treating one as a real option.</p></div><div className="special-grid">
      <article><h3>Arizona State University</h3><p>Professional Flight is based at the Polytechnic campus in Mesa, while NCAA Division I cross country is centered in Tempe. The cross-city schedule and transportation could conflict with practice and flight blocks.</p></article>
      <article><h3>University of Cincinnati</h3><p>Professional Pilot training is associated with the Clermont location, while varsity athletics and most traditional campus life are based at the Uptown campus. Confirm enrollment, transportation and team-practice expectations.</p></article>
      <article><h3>Indiana Wesleyan University</h3><p>IWU has excellent NAIA men's cross country, but its pilot education is primarily an online degree combined with outside partner flight schools. It is not a traditional integrated flight program on the Marion athletics campus.</p></article>
      <article><h3>Kansas State University</h3><p>The strong Part 141 Professional Pilot program is at the Salina Aerospace and Technology Campus, while the NCAA Division I team practices in Manhattan roughly an hour away. That daily combination may not be workable.</p></article>
      <article><h3>Middle Georgia State University</h3><p>The FAA-approved flight program is centered at the specialized Eastman aviation campus. Athletics, housing and other university activities may be based at different MGA locations, so the student's actual home campus matters.</p></article>
      <article><h3>Metropolitan State University of Denver</h3><p>The Professional Flight Officer concentration can support R-ATP eligibility, but flight training is completed through approved outside Part 141 providers at several airports. Transportation and provider availability add another scheduling layer.</p></article>
    </div></section>

    <section className="next-steps"><div><p className="kicker">What to do next</p><h2>Turn the list into a real plan.</h2></div><ol><li><b>Pick five schools.</b><span>Choose a mix of exciting reaches and realistic options.</span></li><li><b>Email each coach.</b><span>Include your verified times, GPA, graduation year, training background, and a link to results.</span></li><li><b>Call each flight program.</b><span>Ask about waitlists, total flight costs, aircraft availability, R-ATP rules, and the FAA medical certificate.</span></li><li><b>Visit your finalists.</b><span>Meet the coach, tour the airport, and ask a current student-athlete how the schedules work together.</span></li></ol></section>

    <section className="source-note"><h2>Use this as a starting point.</h2><p>The information was refreshed in August 2026 from university aviation, athletics, FAA authorization, and published cost pages. Fleets, fees, airline agreements, and team rosters can change. Confirm the details directly before applying or paying a deposit.</p><a href="https://www.ncaa.org/eligibility-center/recruiting" target="_blank" rel="noreferrer">Read NCAA recruiting guidance ↗</a></section>
    <footer className="site-footer"><a className="brand" href="#top"><span className="brand-mark">R</span><span>Runway Routes</span></a><p>Independent college planning guide · Updated August 2026</p><a href="#top">Back to top ↑</a></footer>
  </main>
}
